"""setup

Revision ID: f4a3b98ab1bc
Revises: 
Create Date: 2020-09-25 11:37:19.475179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a3b98ab1bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(length=1048), nullable=False),
    sa.Column('officer_username', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officer_username'], ['officer.username'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('officer')
    # ### end Alembic commands ###
